### ISSUE TITLE
You Win Screen

### ISSUE THREAD

**Issue by Streifenhoernchen** [RunScreaming/RunScreaming-Game#6]
Create a Congratulations! Screen and show it, as soon as the FirstPersonController reaches the goal.
- [x] Attach a Rigidbody to both FPC and Goal-Cube
- [x] Catch Collision Event
- [ ] Load new Scene with Screen OR Show GUI Overlay

**Comment by stefan2904** [comment]
implemented since effcf139622c105213adee3643739e5a82c8f1a4
